[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_program = "8sHV6MjJSkemTc34PXrymjmungpjgf7b1np52eSnoLBx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcelofeitoza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
